[build]
  command = "pnpm build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  staticServerPort = 4000

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express", "serverless-http", "zod", "@supabase/supabase-js"]

[[redirects]]
  from = "/v1/*"
  to = "/.netlify/functions/http"
  status = 200